using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;

namespace DOAN_QLNS
{
    public partial class fmSach_User : DevExpress.XtraEditors.XtraForm
    {
        public fmSach_User()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();            
            load_ds();
        }        
        public fmSach_User(string ma, string ten, string tl, string tg, string nxb, float gn, float gb, int sl, string nd, string nhaxuatban)
        {
            InitializeComponent();
            txtMa.Text = ma;
            txtTen.Text = ten;
            txtTheLoai.Text = tl;
            txtTacGia.Text = tg;
            txtNhaXB.Text = nxb;
            txtGiaNhap.Text = gn.ToString();
            txtGiaBan.Text = gb.ToString();
            txtSoLuong.Text = sl.ToString();
            txtND.Text = nd;
            txtNhaXB.Text = nhaxuatban;            
        }

        public void loadComboBoxTacGia()
        {
            DBService db = new DBService();
            db.openconn();
            DataTable dt = db.getDataTable("select * from NhomTacGia");
            cbTacGia.DataSource = dt;
            cbTacGia.DisplayMember = "NTG_id";
            cbTacGia.ValueMember = "NTG_name";
            if (txtTacGia.Text == "System.Data.DataRowView")
                txtTacGia.Text = "";
            db.closeconn();
        }
        public void loadComboBoxTheLoai()
        {
            DBService db = new DBService();
            db.openconn();
            DataTable dt = db.getDataTable("select * from NhomTheLoai");
            cbTheLoai.DataSource = dt;
            cbTheLoai.DisplayMember = "NTL_id";
            cbTheLoai.ValueMember = "NTL_name";
            if (txtTheLoai.Text == "System.Data.DataRowView")
                txtTheLoai.Text = "";
            db.closeconn();
        }

        public void loadComboBoxNhaXuatBan()
        {
            DBService db = new DBService();
            db.openconn();
            DataTable dt = db.getDataTable("select * from NhomNhaXuatBan");
            cbNhaXuatBan.DataSource = dt;
            cbNhaXuatBan.DisplayMember = "NXB_id";
            cbNhaXuatBan.ValueMember = "NXB_name";
            if (txtNhaXB.Text == "System.Data.DataRowView")
                txtNhaXB.Text = "";
            db.closeconn();
        }

        private void btnThem_Click(object sender, EventArgs e)
        {
            MessageBox.Show("Bạn có muốn thêm sách này không?","Thông báo",MessageBoxButtons.YesNo,MessageBoxIcon.Question);
            DBService db = new DBService();
            db.openconn();
            string ma = txtMa.Text;
            string ten = txtTen.Text;
            string theloai = txtTheLoai.Text;
            string tacgia = txtTacGia.Text;
            string nxb = txtNamXuatBan.Text;
            float gianhap = float.Parse(txtGiaNhap.Text.ToString());
            float giaban = float.Parse(txtGiaBan.Text.ToString());
            int soluong = int.Parse(txtSoLuong.Text.ToString());
            string noidung = txtND.Text;
            string nhaxuatban = txtNhaXB.Text;

            string sql = "insert into DSSACH(Sach_id, Sach_name, Sach_theloai, Sach_tacgia, Sach_nxb, Sach_gianhap, Sach_giaban, Sach_number, Sach_noidung, Sach_nhaxuatban) values('" + ma + "',N'" + ten + "',N'"+theloai+"',N'"+tacgia+"','"+nxb+"'," + gianhap + "," + giaban + "," + soluong + ", '" + noidung + "', N'" + nhaxuatban + "')";
            SqlCommand cmd = new SqlCommand(sql, db.conn);
            SqlTransaction tran = db.conn.BeginTransaction("ThemLopTransaction");
            cmd.Transaction = tran;
            try
            {
                cmd.ExecuteNonQuery();
                tran.Commit();//kết thúc transaction                   
            }
            catch (Exception ex)
            {
                tran.Rollback();//quay lui tới thời điểm beginTran                    
                throw ex;
            }
            db.closeconn();
            MessageBox.Show("Quá trình thêm thành công!", "Chúc mừng", MessageBoxButtons.OK, MessageBoxIcon.Information);
        
        }
            
        public void load_ds()
        {
            gCtrlDSSach.DataSource = null;
            gViewDSSach.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select DSSach.Sach_id as [Mã sách], DSSach.Sach_name as [Tên sách], DSSach.Sach_theloai as [Thể loại], DSSach.Sach_tacgia as [Tác giả], DSSach.Sach_nxb as [Năm xuất bản], DSSach.Sach_gianhap as [Giá nhập], DSSach.Sach_giaban as [Giá bán], DSSach.Sach_number as [Số lượng], DSSach.Sach_noidung as [Nội dung], DSSach.Sach_nhaxuatban as [Nhà xuất bản] from dbo.DSSach DSSach";
            gCtrlDSSach.DataSource = db.getDataReader(sql);
            db.closeconn();
        }

        private void btnThoat_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btnTim_Click(object sender, EventArgs e)
        {
            gCtrlDSSach.DataSource = null;
            gViewDSSach.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select * from dbo.DSSach DSSach where Sach_name = '" + txtTimKiem.Text +"'";
            gCtrlDSSach.DataSource = db.getDataReader(sql);
            db.closeconn();
        }

        private void fmSach_User_Load(object sender, EventArgs e)
        {
            loadComboBoxTacGia();
            loadComboBoxTheLoai();
            loadComboBoxNhaXuatBan();
            load_ds();
        }

        private void cbTacGia_SelectedIndexChanged(object sender, EventArgs e)
        {
            txtTacGia.Text = cbTacGia.SelectedValue.ToString();
        }

        private void cbNhaXuatBan_SelectedIndexChanged(object sender, EventArgs e)
        {
            txtNhaXB.Text = cbNhaXuatBan.SelectedValue.ToString();
        }

        private void cbTheLoai_SelectedIndexChanged(object sender, EventArgs e)
        {
            txtTheLoai.Text = cbTheLoai.SelectedValue.ToString();
        }

        private void btnSua_Click(object sender, EventArgs e)
        {
            DBService db = new DBService();
            db.openconn();
          
            string id = txtMa.Text;
            string name = txtTen.Text;
            string kind = txtTheLoai.Text;
            string author = txtTacGia.Text;
            string year = txtNamXuatBan.Text;
            float gn = float.Parse(txtGiaNhap.Text.ToString());
            float gb = float.Parse(txtGiaBan.Text.ToString());
            int sl = int.Parse(txtSoLuong.Text.ToString());
            string content = txtND.Text;
            string nhxb = txtNhaXB.Text;

            string sql = "update DSSach SET Sach_name = N'" + name + "', Sach_theloai = N'" + kind + "', Sach_tacgia = N'"+author+"',Sach_nxb = '" + year + "',Sach_gianhap = " + gn + " , Sach_giaban = " + gb + ",Sach_number = " + sl + ", Sach_noidung = N'" + content + "', Sach_nhaxuatban = N'"+nhxb+"' WHERE Sach_id = '" + id + "'";
            SqlCommand cmd = new SqlCommand(sql, db.conn);
            SqlTransaction tran = db.conn.BeginTransaction("ThemLopTransaction");
            cmd.Transaction = tran;
            try
            {
                cmd.ExecuteNonQuery();
                tran.Commit();//kết thúc transaction                   
            }
            catch (Exception ex)
            {
                tran.Rollback();//quay lui tới thời điểm beginTran                    
                throw ex;
            }
            db.closeconn();
            MessageBox.Show("Cập nhật thành công", "Chúc mừng", MessageBoxButtons.OK, MessageBoxIcon.Information);
                       
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            load_ds();
        }

        private void gViewDSSach_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {            

            txtMa.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Mã sách").ToString();
            txtTen.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Tên sách").ToString();
            txtTheLoai.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Thể loại").ToString();
            txtTacGia.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Tác giả").ToString();
            txtNamXuatBan.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Năm xuất bản").ToString();
            txtGiaNhap.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Giá nhập").ToString();
            txtGiaBan.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Giá bán").ToString();
            txtSoLuong.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Số lượng").ToString();
            txtNhaXB.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Nhà xuất bản").ToString();
            txtND.Text = gViewDSSach.GetRowCellValue(gViewDSSach.FocusedRowHandle, "Nội dung").ToString();
        }

        private void btnXoa_Click(object sender, EventArgs e)
        {
            txtMa.Text = "";
            txtTen.Text = "";
            txtTheLoai.Text = "";
            txtTacGia.Text = "";
            txtSoLuong.Text = "";
            txtNhaXB.Text = "";
            cbTacGia.Text = "";
            cbTheLoai.Text = "";
            cbNhaXuatBan.Text = "";
            txtND.Text = "";
            txtNamXuatBan.Text = "";
            txtGiaBan.Text = "";
            txtGiaNhap.Text = "";
        }
    }
}