using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;

namespace DOAN_QLNS
{
    public partial class fmSach_KH : DevExpress.XtraEditors.XtraForm
    {
        public fmSach_KH()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void gridView_DSSach_RowClick(object sender, RowClickEventArgs e)
        {
            picSach.ImageLocation = "Book/" + gridView_DSSach.GetRowCellValue(gridView_DSSach.FocusedRowHandle, "Mã sách").ToString() + ".jpg";
        }
       
        private void fmSach_KH_Load(object sender, EventArgs e)
        {
            gridView_DSSach.CustomDrawRowIndicator += gridView1_CustomDrawRowIndicator;
        }
        void gridView1_CustomDrawRowIndicator(object sender, DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs e)
        {
            if (!gridView_DSSach.IsGroupRow(e.RowHandle)) //Nếu không phải là Group
            {
                if (e.Info.IsRowIndicator) //Nếu là dòng Indicator
                {
                    if (e.RowHandle < 0)
                    {
                        e.Info.ImageIndex = 0;
                        e.Info.DisplayText = string.Empty;
                    }
                    else
                    {
                        e.Info.ImageIndex = -1; //Không hiển thị hình
                        e.Info.DisplayText = (e.RowHandle + 1).ToString(); //Số thứ tự tăng dần
                    }
                    SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font); //Lấy kích thước của vùng hiển thị Text
                    Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                    BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView_DSSach); })); //Tăng kích thước nếu Text vượt quá
                }
            }
            else
            {
                e.Info.ImageIndex = -1;
                e.Info.DisplayText = string.Format("[{0}]", (e.RowHandle * -1)); //Nhân -1 để đánh lại số thứ tự tăng dần
                SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font);
                Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView_DSSach); }));
            }
        }
        bool cal(Int32 _Width, GridView _View)
        {
            _View.IndicatorWidth = _View.IndicatorWidth < _Width ? _Width : _View.IndicatorWidth;
            return true;
        }
        public void load_dssach()
        {
            gridControlSach.DataSource = null;
            gridView_DSSach.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select DSSach.Sach_id as [Mã sách], DSSach.Sach_name as [Tên sách],DSSach.Sach_theloai as [Thể loại], DSSach.Sach_tacgia as [Tác giả],DSSach.Sach_nxb as [Năm xuất bản],DSSach.Sach_giaban as [Giá bán], DSSach.Sach_noidung as [Nội dung] from dbo.DSSach DSSach";
            gridControlSach.DataSource = db.getDataReader(sql);
            db.closeconn();
        }       
        private void btnTim_Click(object sender, EventArgs e)
        {
            gridControlSach.DataSource = null;
            gridView_DSSach.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select * from dbo.DSSach ds where ds.Sach_name = N'" + txtTimKiem.Text + "'";
            gridControlSach.DataSource = db.getDataReader(sql);
            db.closeconn();     
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            load_dssach();
        }

       
    }
}