using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;

namespace DOAN_QLNS
{
    public partial class fmTacGia_KH : DevExpress.XtraEditors.XtraForm
    {
        string imageLocation = "";  
        public fmTacGia_KH()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void gridView1_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            picTG.ImageLocation = "TacGia/" + gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "Mã tác giả").ToString() + ".jpg";            
        }

        private void fmTacGia_Load(object sender, EventArgs e)
        {
            gridView1.CustomDrawRowIndicator += gridView1_CustomDrawRowIndicator;
        }
        void gridView1_CustomDrawRowIndicator(object sender, DevExpress.XtraGrid.Views.Grid.RowIndicatorCustomDrawEventArgs e)
        {
            if (!gridView1.IsGroupRow(e.RowHandle)) //Nếu không phải là Group
            {
                if (e.Info.IsRowIndicator) //Nếu là dòng Indicator
                {
                    if (e.RowHandle < 0)
                    {
                        e.Info.ImageIndex = 0;
                        e.Info.DisplayText = string.Empty;
                    }
                    else
                    {
                        e.Info.ImageIndex = -1; //Không hiển thị hình
                        e.Info.DisplayText = (e.RowHandle + 1).ToString(); //Số thứ tự tăng dần
                    }
                    SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font); //Lấy kích thước của vùng hiển thị Text
                    Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                    BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); })); //Tăng kích thước nếu Text vượt quá
                }
            }
            else
            {
                e.Info.ImageIndex = -1;
                e.Info.DisplayText = string.Format("[{0}]", (e.RowHandle * -1)); //Nhân -1 để đánh lại số thứ tự tăng dần
                SizeF _Size = e.Graphics.MeasureString(e.Info.DisplayText, e.Appearance.Font);
                Int32 _Width = Convert.ToInt32(_Size.Width) + 20;
                BeginInvoke(new MethodInvoker(delegate { cal(_Width, gridView1); }));
            }
        }
        bool cal(Int32 _Width, GridView _View)
        {
            _View.IndicatorWidth = _View.IndicatorWidth < _Width ? _Width : _View.IndicatorWidth;
            return true;
        }
        public void load_dstacgia()
        {
            gridControlTG.DataSource = null;
            gridView1.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select NHOMTACGIA.NTG_id as [Mã tác giả], NHOMTACGIA.NTG_name as [Tên tác giả],NHOMTACGIA.NTG_note as [Ghi chú] from dbo.NHOMTACGIA NHOMTACGIA";
            gridControlTG.DataSource = db.getDataReader(sql);
            db.closeconn();
        }       
        private void btnTim_Click(object sender, EventArgs e)
        {
            gridControlTG.DataSource = null;
            gridView1.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select * from dbo.NhomTacGia tg where tg.NTG_name = N'" + txtTimKiem.Text + "'";
            gridControlTG.DataSource = db.getDataReader(sql);
            db.closeconn();     
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            load_dstacgia();
        }

        private void btnChiTiet_Click(object sender, EventArgs e)
        {
            OpenFileDialog dialog = new OpenFileDialog();
            dialog.Filter = "png files(*.png)|*.png|jpg files(*.jpg)|*.jpg|All files(*.*)|*.*";
            if (dialog.ShowDialog() == DialogResult.OK)
            {
                imageLocation = dialog.FileName.ToString();                
            }
        }
    }
}

