using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;

namespace DOAN_QLNS
{
    public partial class fmKhachHang : DevExpress.XtraEditors.XtraForm
    {
        public fmKhachHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            load_dskh();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void btThemNV_Click(object sender, EventArgs e)
        {
            fmCapNhatKhachHang fm = new fmCapNhatKhachHang();
            fm.ShowDialog();
            load_dskh();
        }

        private void btSuaKH_Click(object sender, EventArgs e)
        {
            string ma; string ten; string sdt; string mail; string gc; float sotienno;

            ma = gView_DSKH.GetRowCellValue(gView_DSKH.FocusedRowHandle, "Mã khách hàng").ToString();
            ten = gView_DSKH.GetRowCellValue(gView_DSKH.FocusedRowHandle, "Tên khách hàng").ToString();
            sdt = gView_DSKH.GetRowCellValue(gView_DSKH.FocusedRowHandle, "Số điện thoại").ToString();
            mail = gView_DSKH.GetRowCellValue(gView_DSKH.FocusedRowHandle, "Email").ToString();
            sotienno = float.Parse(gView_DSKH.GetRowCellValue(gView_DSKH.FocusedRowHandle, "Số tiền nợ").ToString());
            gc = gView_DSKH.GetRowCellValue(gView_DSKH.FocusedRowHandle, "Ghi chú").ToString();


            fmCapNhatKhachHang fm = new fmCapNhatKhachHang(ma, ten, sdt, mail, sotienno, gc);
            fm.ShowDialog();
            load_dskh();
        }

       
        public void load_dskh()
        {
            gControl_DSKH.DataSource = null;
            gView_DSKH.Columns.Clear();            
            DBService db = new DBService();
            db.openconn();
            string sql = "select KhachHang.KH_id as [Mã khách hàng],KhachHang.KH_name as [Tên khách hàng],KhachHang.KH_number as [Số điện thoại],KhachHang.KH_mail as [Email], KhachHang.KH_note as [Ghi chú], KhachHang.KH_scores as [Số tiền nợ] from dbo.KhachHang KhachHang";
            gControl_DSKH.DataSource = db.getDataReader(sql);
            db.closeconn();
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            load_dskh();
        }

        private void btnTim_Click(object sender, EventArgs e)
        {
            gControl_DSKH.DataSource = null;
            gView_DSKH.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select KhachHang.KH_id as [Mã khách hàng],KhachHang.KH_name as [Tên khách hàng],KhachHang.KH_number as [Số điện thoại],KhachHang.KH_mail as [Email], KhachHang.KH_note as [Ghi chú], KhachHang.KH_scores as [Số tiền nợ] from dbo.KhachHang KhachHang where KH_id = '"+txtTimKiem.Text+"'";
            gControl_DSKH.DataSource = db.getDataReader(sql);
            db.closeconn();
        }
    }
}