using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;

namespace DOAN_QLNS
{
    public partial class fmNhaXuatBan : DevExpress.XtraEditors.XtraForm
    {
        public fmNhaXuatBan()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            load_dsnxb();
        }

        private void btThemNV_Click(object sender, EventArgs e)
        {
            fmCapNhatNhaXuatBan fm = new fmCapNhatNhaXuatBan();
            fm.ShowDialog();
            load_dsnxb();
        }

        private void btXoa_Click(object sender, EventArgs e)
        {
            DBService db = new DBService();
            db.openconn();
            string sql2 = "DELETE FROM NHOMNHAXUATBAN WHERE NXB_id = '" + gridView_NXB.GetRowCellValue(gridView_NXB.FocusedRowHandle, "Mã Nhà xuất bản").ToString() + "'";
            SqlCommand cmd2 = new SqlCommand(sql2, db.conn);
            SqlTransaction tran2 = db.conn.BeginTransaction("ThemLopTransaction");
            cmd2.Transaction = tran2;
            try
            {
                cmd2.ExecuteNonQuery(); // xoa taikhoan truoc
                tran2.Commit();//kết thúc transaction               

            }
            catch (Exception ex)
            {
                tran2.Rollback();
                throw ex;
            }
            db.closeconn();
            MessageBox.Show("Thành công", "Chúc mừng", MessageBoxButtons.OK, MessageBoxIcon.Information);
            load_dsnxb();
        }

        private void btSuaNV_Click(object sender, EventArgs e)
        {
            string ma; string ten; string sdt; string dc; string gc; 

            ma = gridView_NXB.GetRowCellValue(gridView_NXB.FocusedRowHandle, "Mã Nhà xuất bản").ToString();
            ten = gridView_NXB.GetRowCellValue(gridView_NXB.FocusedRowHandle, "Tên nhà xuất bản").ToString();            
            sdt = gridView_NXB.GetRowCellValue(gridView_NXB.FocusedRowHandle, "Số điện thoại").ToString();
            dc = gridView_NXB.GetRowCellValue(gridView_NXB.FocusedRowHandle, "Địa chỉ").ToString();
            gc = gridView_NXB.GetRowCellValue(gridView_NXB.FocusedRowHandle, "Ghi chú").ToString();
            fmCapNhatNhaXuatBan fm = new fmCapNhatNhaXuatBan(ma, ten, sdt, dc, gc);
            fm.ShowDialog();
            load_dsnxb();
        }
        public void load_dsnxb()
        {
            gridControl_NXB.DataSource = null;
            gridView_NXB.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select NhomNhaXuatBan.NXB_id as [Mã Nhà xuất bản], NhomNhaXuatBan.NXB_name as [Tên nhà xuất bản], NhomNhaXuatBan.NXB_number as [Số điện thoại], NhomNhaXuatBan.NXB_address as [Địa chỉ],NhomNhaXuatBan.NXB_note as [Ghi chú] from dbo.NhomNhaXuatBan NhomNhaXuatBan";
            gridControl_NXB.DataSource = db.getDataReader(sql);
            db.closeconn();

        }

        private void btnTim_Click(object sender, EventArgs e)
        {
            gridControl_NXB.DataSource = null;
            gridView_NXB.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select * from dbo.NhomNhaXuatBan nxb where nxb.NXB_name = N'" + txtTimKiem.Text + "'";
            gridControl_NXB.DataSource = db.getDataReader(sql);
            db.closeconn();        
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            load_dsnxb();
        }       
    }
}