using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;

namespace DOAN_QLNS
{
    public partial class fmNhanVien : DevExpress.XtraEditors.XtraForm
    {
        public fmNhanVien()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //sqlDataSource1.Fill();
            load_dsnv();
        }

        private void btThemNV_Click(object sender, EventArgs e)
        {
            fmCapNhatDSNV fm = new fmCapNhatDSNV();
            fm.ShowDialog();
            load_dsnv();
        }

        private void btSuaNV_Click(object sender, EventArgs e)
        {
            string ma; string ten; string gt; DateTime ns; DateTime nvl; string sdt; string dc; string gc; string user; string pass; string chucvu;

            ma = gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Mã nhân viên").ToString();
            ten = gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Họ và tên").ToString();
            gt = gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Giới tính").ToString();
            sdt = gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Số điện thoại").ToString();
            dc = gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Địa chỉ").ToString();
            gc = gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Ghi chú").ToString();
            user = gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Tài khoản").ToString();
            pass = gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Mật khẩu").ToString();
            chucvu = gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Chức vụ").ToString();
            ns = Convert.ToDateTime(gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Ngày sinh").ToString());
            nvl = Convert.ToDateTime(gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Ngày làm").ToString());

            
            fmCapNhatDSNV fm = new fmCapNhatDSNV(ma,ten,gt,ns,nvl,sdt,dc,gc,user,pass, chucvu);
            fm.ShowDialog();
            load_dsnv();
        }

        private void btXoa_Click(object sender, EventArgs e)
        {
            DBService db = new DBService();
            db.openconn();
            string sql2 = "DELETE FROM TAIKHOAN WHERE NV_id = '" + gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Mã nhân viên").ToString() + "'"; // xoa tk
            SqlCommand cmd2 = new SqlCommand(sql2, db.conn);
            SqlTransaction tran2 = db.conn.BeginTransaction("ThemLopTransaction");
            cmd2.Transaction = tran2;
            try
            {
                cmd2.ExecuteNonQuery(); // xoa taikhoan truoc
                tran2.Commit();//kết thúc transaction               

            }
            catch (Exception ex)
            {                
                tran2.Rollback();
                throw ex;
            }

            string sql1 = "DELETE FROM NHANVIEN WHERE NV_id = '" + gView_DSNV.GetRowCellValue(gView_DSNV.FocusedRowHandle, "Mã nhân viên").ToString() +"'"; // xoa nv           
            SqlCommand cmd1 = new SqlCommand(sql1, db.conn);
            //đánh dấu điểm bắt đầu
            SqlTransaction tran1 = db.conn.BeginTransaction("ThemLopTransaction");
            cmd1.Transaction = tran1;
                     
            try
            {               
                cmd1.ExecuteNonQuery(); // roi xoa nhanvien
                tran1.Commit();//kết thúc transaction

            }
            catch (Exception ex)
            {
                tran1.Rollback();//quay lui tới thời điểm beginTran                
                throw ex;
            }
            db.closeconn();
            MessageBox.Show("Thành công", "Chúc mừng",MessageBoxButtons.OK, MessageBoxIcon.Information);
            load_dsnv();
        }
        public void load_dsnv()
        {
            gCtrl_DSNV.DataSource = null;
            gView_DSNV.Columns.Clear();            
            DBService db = new DBService();
            db.openconn();
            string sql = "select NhanVien.NV_id as [Mã nhân viên], NhanVien.NV_name as [Họ và tên],NhanVien.NV_gender as [Giới tính], NhanVien.NV_birthday as [Ngày sinh],NhanVien.NV_datework as [Ngày làm],NhanVien.NV_number as [Số điện thoại],NhanVien.NV_address as [Địa chỉ], NhanVien.NV_note as [Ghi chú], tk.Username as [Tài khoản], tk.Pass as [Mật khẩu], tk.Acc_Type as [Chức vụ] from dbo.NhanVien NhanVien join TaiKhoan tk on NhanVien.NV_id = tk.NV_id";
            gCtrl_DSNV.DataSource = db.getDataReader(sql);
            db.closeconn();
        }       
        
        private void btnTim_Click(object sender, EventArgs e)
        {
            gCtrl_DSNV.DataSource = null;
            gView_DSNV.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select * from dbo.NhanVien Nv join TaiKhoan tk on nv.NV_id = tk.NV_id where nv.NV_name = N'"+txtTimKiem.Text+"'";
            gCtrl_DSNV.DataSource = db.getDataReader(sql);
            db.closeconn();          
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            load_dsnv();
        }
       
    }
}