using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;

namespace DOAN_QLNS
{
    public partial class fmNhaCungCap : DevExpress.XtraEditors.XtraForm
    {
        public fmNhaCungCap()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            load_dsncc();
        }

        private void btThemNV_Click(object sender, EventArgs e)
        {
            fmCapNhapNCC fm = new fmCapNhapNCC();
            fm.ShowDialog();
            load_dsncc();
        }

        private void btSuaNV_Click(object sender, EventArgs e)
        {
            string ma; string ten; string sdt; string dc; string gc;

            ma = gView_NCC.GetRowCellValue(gView_NCC.FocusedRowHandle, "Mã NCC").ToString();
            ten = gView_NCC.GetRowCellValue(gView_NCC.FocusedRowHandle, "Tên NCC").ToString();
            sdt = gView_NCC.GetRowCellValue(gView_NCC.FocusedRowHandle, "Số điện thoại").ToString();
            dc = gView_NCC.GetRowCellValue(gView_NCC.FocusedRowHandle, "Địa chỉ").ToString();
            gc = gView_NCC.GetRowCellValue(gView_NCC.FocusedRowHandle, "Ghi chú").ToString();
            fmCapNhapNCC fm = new fmCapNhapNCC(ma, ten, sdt, dc, gc);
            fm.ShowDialog();
            load_dsncc();
        }

        private void btXoa_Click(object sender, EventArgs e)
        {
            DBService db = new DBService();
            db.openconn();
            string sql1 = "DELETE FROM NHOMTHELOAI WHERE NCC_id = '" + gView_NCC.GetRowCellValue(gView_NCC.FocusedRowHandle, "Mã NCC").ToString() + "'";
            SqlCommand cmd1 = new SqlCommand(sql1, db.conn);
            //đánh dấu điểm bắt đầu
            SqlTransaction tran1 = db.conn.BeginTransaction("ThemLopTransaction");
            cmd1.Transaction = tran1;
            try
            {
                cmd1.ExecuteNonQuery();
                tran1.Commit();
            }
            catch (Exception ex)
            {
                tran1.Rollback();//quay lui tới thời điểm beginTran               
                throw ex;
            }
            db.closeconn();
            MessageBox.Show("Xóa thành công", "Chúc mừng", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }
        public void load_dsncc()
        {
            gCtrol_NCC.DataSource = null;
            gView_NCC.Columns.Clear();

            DBService db = new DBService();
            db.openconn();
            string sql = "select NHOMNHACUNGCAP.NCC_id as [Mã NCC],  NHOMNHACUNGCAP.NCC_name as [Tên NCC], NHOMNHACUNGCAP.NCC_number as [Số điện thoại], NHOMNHACUNGCAP.NCC_address as [Địa chỉ], NHOMNHACUNGCAP.NCC_note as [Ghi chú] from dbo.NHOMNHACUNGCAP NHOMNHACUNGCAP";
            gCtrol_NCC.DataSource = db.getDataReader(sql);
            db.closeconn();
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            load_dsncc();
        }

        private void btnTim_Click(object sender, EventArgs e)
        {
            gCtrol_NCC.DataSource = null;
            gView_NCC.Columns.Clear();
         
            DBService db = new DBService();
            db.openconn();
            string sql = "select NHOMNHACUNGCAP.NCC_id as [Mã NCC],  NHOMNHACUNGCAP.NCC_name as [Tên NCC], NHOMNHACUNGCAP.NCC_number as [Số điện thoại], NHOMNHACUNGCAP.NCC_address as [Địa chỉ], NHOMNHACUNGCAP.NCC_note as [Ghi chú] from dbo.NHOMNHACUNGCAP NHOMNHACUNGCAP where NCC_id = '"+ txtTimKiem.Text +"'";
            gCtrol_NCC.DataSource = db.getDataReader(sql);
            db.closeconn();
        }      
    }
}