using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;

namespace DOAN_QLNS
{
    public partial class fmTacGia_User : DevExpress.XtraEditors.XtraForm
    {
        public fmTacGia_User()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            load_dstacgia();
        }
        public void load_dstacgia()
        {
            gridControl_TG.DataSource = null;
            gridView_TG.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select NHOMTACGIA.NTG_id as [Mã tác giả], NHOMTACGIA.NTG_name as [Tên tác giả],NHOMTACGIA.NTG_note as [Ghi chú] from dbo.NHOMTACGIA NHOMTACGIA";
            gridControl_TG.DataSource = db.getDataReader(sql);
            db.closeconn();
        }

        private void btnTim_Click(object sender, EventArgs e)
        {
            gridControl_TG.DataSource = null;
            gridView_TG.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select * from dbo.NhomTacGia tg where tg.NTG_name = N'" + txtTimKiem.Text + "'";
            gridControl_TG.DataSource = db.getDataReader(sql);
            db.closeconn();     
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            load_dstacgia();
        }

        private void btXoa_Click(object sender, EventArgs e)
        {
            MessageBox.Show("Bạn có chắc chắn xóa không?", "Cảnh báo", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            DBService db = new DBService();
            db.openconn();
            string sql1 = "DELETE FROM NHOMTACGIA WHERE NTG_id = '" + gridView_TG.GetRowCellValue(gridView_TG.FocusedRowHandle, "Mã tác giả").ToString() + "'";
            SqlCommand cmd1 = new SqlCommand(sql1, db.conn);
            //đánh dấu điểm bắt đầu
            SqlTransaction tran1 = db.conn.BeginTransaction("ThemLopTransaction");
            cmd1.Transaction = tran1;
            try
            {
                cmd1.ExecuteNonQuery();
                tran1.Commit();
            }
            catch (Exception ex)
            {
                tran1.Rollback();//quay lui tới thời điểm beginTran               
                throw ex;
            }
            db.closeconn();
            MessageBox.Show("Xóa thành công", "Chúc mừng", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void btSuaNV_Click(object sender, EventArgs e)
        {
            string ma; string ten; string gc;

            ma = gridView_TG.GetRowCellValue(gridView_TG.FocusedRowHandle, "Mã tác giả").ToString();
            ten = gridView_TG.GetRowCellValue(gridView_TG.FocusedRowHandle, "Tên tác giả").ToString();
            gc = gridView_TG.GetRowCellValue(gridView_TG.FocusedRowHandle, "Ghi chú").ToString();

            fmCapNhatTacGia fm = new fmCapNhatTacGia(ma, ten, gc);
            fm.ShowDialog();
            load_dstacgia();
        }

        private void btThemNV_Click(object sender, EventArgs e)
        {
            fmCapNhatTacGia fm = new fmCapNhatTacGia();
            fm.ShowDialog();
            load_dstacgia();
        }       
    }
}