using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;

namespace DOAN_QLNS
{
    public partial class fmTheLoaiSach : DevExpress.XtraEditors.XtraForm
    {
        public fmTheLoaiSach()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
            load_dstls();
        }

        public void load_dstls()
        {
            gControl_TheLoaiSach.DataSource = null;
            gView_TheLoaiSach.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select NHOMTHELOAI.NTL_id as [Mã thể loại], NHOMTHELOAI.NTL_name as [Tên thể loại], NHOMTHELOAI.NTL_note as [Ghi chú] from dbo.NHOMTHELOAI NHOMTHELOAI";
            gControl_TheLoaiSach.DataSource = db.getDataReader(sql);
            db.closeconn();
        }
        private void btThemNV_Click(object sender, EventArgs e)
        {
            fmCapNhatTheLoaiSach fm = new fmCapNhatTheLoaiSach();
            fm.ShowDialog();
            load_dstls();
        }

        private void btSuaNV_Click(object sender, EventArgs e)
        {
            string ma; string ten; string gc;

            ma = gView_TheLoaiSach.GetRowCellValue(gView_TheLoaiSach.FocusedRowHandle, "Mã thể loại").ToString();
            ten = gView_TheLoaiSach.GetRowCellValue(gView_TheLoaiSach.FocusedRowHandle, "Tên thể loại").ToString();
            gc = gView_TheLoaiSach.GetRowCellValue(gView_TheLoaiSach.FocusedRowHandle, "Ghi chú").ToString();
            
            fmCapNhatTheLoaiSach fm = new fmCapNhatTheLoaiSach(ma, ten, gc);
            fm.ShowDialog();
            load_dstls();
        }

        private void btXoa_Click(object sender, EventArgs e)
        {
            MessageBox.Show("Bạn có muốn xóa không?","Cảnh báo",MessageBoxButtons.YesNo,MessageBoxIcon.Warning);
            DBService db = new DBService();
            db.openconn();
            string sql1 = "DELETE FROM NHOMTHELOAI WHERE NTL_id = '" + gView_TheLoaiSach.GetRowCellValue(gView_TheLoaiSach.FocusedRowHandle, "Mã thể loại").ToString() + "'";                       
            SqlCommand cmd1 = new SqlCommand(sql1, db.conn);            
            //đánh dấu điểm bắt đầu
            SqlTransaction tran1 = db.conn.BeginTransaction("ThemLopTransaction");
            cmd1.Transaction = tran1;                     
            try
            {
                cmd1.ExecuteNonQuery(); 
                tran1.Commit();               
            }
            catch (Exception ex)
            {
                tran1.Rollback();//quay lui tới thời điểm beginTran               
                throw ex;
            }
            db.closeconn();
            MessageBox.Show("Bạn có chắc chắn muốn xóa không?","Cảnh báo",MessageBoxButtons.YesNo,MessageBoxIcon.Warning);
            MessageBox.Show("Xóa thành công", "Chúc mừng", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            load_dstls();
        }

        private void btnTim_Click(object sender, EventArgs e)
        {
            gControl_TheLoaiSach.DataSource = null;
            gView_TheLoaiSach.Columns.Clear();
            DBService db = new DBService();
            db.openconn();
            string sql = "select NHOMTHELOAI.NTL_id as [Mã thể loại], NHOMTHELOAI.NTL_name as [Tên thể loại], NHOMTHELOAI.NTL_note as [Ghi chú] from dbo.NHOMTHELOAI NHOMTHELOAI where NHOMTHELOAI.NTL_name = '"+ txtTimKiem.Text + "'";
            gControl_TheLoaiSach.DataSource = db.getDataReader(sql);
            db.closeconn();
        }
      
    }
}